### PR TITLE
Batch 25 flipping cards

### PR DESCRIPTION
**Pull request by jadjoubran**
We're still missing the mugshots and a few design fixes

### CODE REVIEW

**Comment by cveneziani** [comment]
@jadjoubran just a small issue, when hovering on a card, we don't have access anymore to the portfolio link. When clicking on the link icon, it's supposed to open the portfolio in a new tab.

**Comment by jadjoubran** [comment]
Okay, will ping you when I push a fix :D

**Comment by cveneziani** [comment]
Thanks :)

**Comment by jadjoubran** [comment]
Ping @cveneziani

**Comment by cveneziani** [comment]
Thanks!

**Pull request merged**
